apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: appsody-build-test
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/appsody-build-test
            imagePullPolicy: Always
            ports:
            - containerPort: 3000
